<h1><?php echo __('The base application in PhalconPHP')?></h1>
<p><?php echo __('Use this application as a way to quick start any new project.')?></p>
<hr />
<h3><?php echo __('Components')?>:</h3>
<ul>
    <li>Bootstrap file</li>
    <li>Config file</li>
    <li>Frontend/Backend modules</li>
    <li>Library
        <ul>
            <li>Auth</li>
            <li>Arr</li>
            <li>Debug</li>
            <li>I18n</li>
        </ul>
    </li>
    <li>User
        <ul>
            <li>Models</li>
            <li>Auth schema mysql</li>
        </ul>
    </li>
    <li>Twitter Bootstrap</li>
</ul>
<hr />
<h3><?php echo __('Language')?>:</h3>
<ul>
    <li><?php echo \Phalcon\Tag::linkTo('lang/set/en-gb', __('English'))?></li>
    <li><?php echo \Phalcon\Tag::linkTo('lang/set/pl-pl', __('Polish'))?></li>
</ul>