<?php /**
 * Error 404 View
 * 
 * @package     base-app
 * @category    View
 * @version     1.1
 */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo __('Error :code', array(':code' => 404)) ?></title>
    </head>
    <body>
        <h1><?php echo __('Error :code', array(':code' => 404)) . ' - ' . __('Page not found.') ?></h1>
    </body>
</html>