<?php /**
 * Admin's Template View
 * 
 * @package     base-app
 * @category    View
 * @version     1.1
 */ ?><?php

 use \Phalcon\Tag,
     \Baseapp\Library\I18n; ?>
<!DOCTYPE html>
<html lang="<?php echo substr(I18n::instance()->lang(), 0, 2) ?>">
    <head>
        <meta charset="utf-8">
        <?php echo Tag::getTitle() ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo Tag::stylesheetLink('css/bootstrap.min.css') ?>
        <style>
            body { padding-top: 45px; }
        </style>
        <?php echo Tag::stylesheetLink('css/bootstrap-responsive.min.css') ?>
        <?php echo Tag::stylesheetLink('css/app.css') ?>

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <?php echo Tag::javascriptInclude('js/html5shiv.js') ?>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="shortcut icon" href="<?php echo $this->url->get('favicon.ico') ?>">
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php echo Tag::linkTo(array(NULL, $this->config->site->name, 'class' => 'brand')) ?>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><?php echo Tag::linkTo(NULL, __('Home')) ?></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">
            <?php echo $this->view->getContent() ?>
        </div> <!-- /container -->

        <?php echo Tag::javascriptInclude('js/jquery.min.js') ?>
        <?php echo Tag::javascriptInclude('js/bootstrap.min.js') ?>
    </body>
</html>